version: '3.2'

volumes:
  loyalty_db_vol:

services:
  loyalty_db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=bot_db
    volumes:
      - loyalty_db_vol:/var/lib/postgresql/data
    ports:
      - "5432:5432"